### ISSUE TITLE
You must run this script from the same directory as it is in!

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dxskj/firmware-mod-kit#92]
```
terminal shows that “You must run this script from the same directory as it 
is in!
”
when i run 

./old-extract.sh ./whr-g300nv2-firmware-MULTI.mentohust.GUI.bin rom/
```

Original issue reported on code.google.com by `cuiweiqi...@gmail.com` on 10 Apr 2013 at 5:56

**Comment by GoogleCodeExporter** [comment]
```
I fixed it in a commit I just made.
```

Original comment by `jeremy.collake@gmail.com` on 10 Apr 2013 at 6:08
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
thank you 
it seems old-extract.sh has a mistake in line 84
but when i put it right，i get a mistake:
[Ouranos@Ouranos trunk]$ ./extract-firmware.sh 
whr-g300nv2-firmware-MULTI.mentohust.GUI.bin 
Firmware Mod Kit (build-ng) 0.79, (c)2011-2012 Craig Heffner, Jeremy Collake

Scanning firmware...
Traceback (most recent call last):
  File "./src/binwalk-1.0/src/bin/binwalk-script", line 5, in <module>
    import binwalk
  File "/home/Ouranos/桌面/firmware-mod-kit-read-only/trunk/src/binwalk-1.0/src/bin/binwalk/__init__.py", line 12, in <module>
    class Binwalk:
  File "/home/Ouranos/桌面/firmware-mod-kit-read-only/trunk/src/binwalk-1.0/src/bin/binwalk/__init__.py", line 28, in Binwalk
    DEFAULT_FLAGS = magic.MAGIC_NO_CHECK_TEXT | magic.MAGIC_NO_CHECK_ENCODING | magic.MAGIC_NO_CHECK_APPTYPE | magic.MAGIC_NO_CHECK_TOKENS
AttributeError: 'module' object has no attribute 'MAGIC_NO_CHECK_TEXT'
sort: 打开失败: 
/home/Ouranos/桌面/firmware-mod-kit-read-only/trunk/fmk/logs/binwalk.log: 
没有那个文件或目录
Extracting 0 bytes of  header image at offset 0
ERROR: No supported file system found! Aborting...

please help me....
my firmware is in 
https://code.google.com/p/mentohust-wrt/downloads/detail?name=whr-g300nv2-firmwa
re-MULTI.mentohust.GUI.7z&can=2&q= 
```

Original comment by `cuiweiqi...@gmail.com` on 10 Apr 2013 at 6:19

**Comment by GoogleCodeExporter** [comment]
```
Undo your changes and try again. I have no idea what mods you made. I fixed the 
old extraction scripts, though don't bother with them.
```

Original comment by `jeremy.collake@gmail.com` on 10 Apr 2013 at 6:22

**Comment by GoogleCodeExporter** [comment]
```
thak you very much  
I've try the oher ways
```

Original comment by `cuiweiqi...@gmail.com` on 10 Apr 2013 at 6:34
